-- Listar todos los registro por Alquiler Apartamento
CREATE PROCEDURE SP_L_ALQUILER_01
    @ID_USER INT,
    @ID_ESTADO INT
AS
BEGIN
    SELECT
        A.ID_ALQUILER_APTO,
        A.FE_INICIO,
        A.FE_FINAL,
        A.NOM_ARRENDATARIO,
        A.APE_ARRENDATARIO,
        A.MONTO,
        A.DPI_ARRENDATARIO,
        E.DESCRIPCION AS ESTADO,
        A.OBSERVACIONES,
        A.FE_CREACION
    FROM TRZ6_ALQUILER_APTO A
    INNER JOIN TRZ6_CAT_ESTADO E ON A.ID_ESTADO = E.ID_ESTADO
    WHERE A.ID_USER = @ID_USER
      AND A.ID_ESTADO = @ID_ESTADO
END
GO

-- Listar registro por ID
CREATE PROCEDURE SP_L_ALQUILER_02
    @ID_ALQUILER_APTO INT
AS
BEGIN
    SELECT
        A.ID_ALQUILER_APTO,
        A.ID_USER,
        A.FE_INICIO,
        A.FE_FINAL,
        A.NOM_ARRENDATARIO,
        A.APE_ARRENDATARIO,
        A.MONTO,
        A.DPI_ARRENDATARIO,
        E.DESCRIPCION AS ESTADO,
        A.OBSERVACIONES,
        A.FE_CREACION
    FROM TRZ6_ALQUILER_APTO A
    INNER JOIN TRZ6_CAT_ESTADO E ON A.ID_ESTADO = E.ID_ESTADO
    WHERE A.ID_ALQUILER_APTO = @ID_ALQUILER_APTO
END

-- Eliminar registro
CREATE PROCEDURE SP_D_ALQUILER_01
    @ID_ALQUILER_APTO INT
AS
BEGIN
    DELETE FROM TRZ6_ALQUILER_APTO
    WHERE ID_ALQUILER_APTO = @ID_ALQUILER_APTO
END
GO

-- Insertar nuevo registro
CREATE PROCEDURE SP_I_ALQUILER_01
    @ID_USER INT,
    @FE_INICIO DATE,
    @FE_FINAL DATE = NULL,
    @NOM_ARRENDATARIO VARCHAR(150),
    @APE_ARRENDATARIO VARCHAR(150),
    @MONTO DECIMAL(18,2),
    @DPI_ARRENDATARIO VARCHAR(50),
    @FOTO_DPI VARBINARY(MAX) = NULL,
    @ID_ESTADO INT,
    @OBSERVACIONES VARCHAR(300) = NULL
AS
BEGIN
    INSERT INTO TRZ6_ALQUILER_APTO (
        ID_USER,
        FE_INICIO,
        FE_FINAL,
        NOM_ARRENDATARIO,
        APE_ARRENDATARIO,
        MONTO,
        DPI_ARRENDATARIO,
        FOTO_DPI,
        ID_ESTADO,
        OBSERVACIONES,
        FE_CREACION
    )
    VALUES (
        @ID_USER,
        @FE_INICIO,
        @FE_FINAL,
        @NOM_ARRENDATARIO,
        @APE_ARRENDATARIO,
        @MONTO,
        @DPI_ARRENDATARIO,
        @FOTO_DPI,
        @ID_ESTADO,
        @OBSERVACIONES,
        SYSUTCDATETIME()
    )
END
GO

-- Update registro
CREATE PROCEDURE SP_U_ALQUILER_01
    @ID_ALQUILER_APTO INT,
    @ID_USER INT,
    @FE_INICIO DATE,
    @FE_FINAL DATE = NULL,
    @NOM_ARRENDATARIO VARCHAR(150),
    @APE_ARRENDATARIO VARCHAR(150),
    @MONTO DECIMAL(18,2),
    @DPI_ARRENDATARIO VARCHAR(50),
    @FOTO_DPI VARBINARY(MAX) = NULL,
    @ID_ESTADO INT,
    @OBSERVACIONES VARCHAR(300) = NULL
AS
BEGIN
    UPDATE TRZ6_ALQUILER_APTO
    SET
        ID_USER = @ID_USER,
        FE_INICIO = @FE_INICIO,
        FE_FINAL = @FE_FINAL,
        NOM_ARRENDATARIO = @NOM_ARRENDATARIO,
        APE_ARRENDATARIO = @APE_ARRENDATARIO,
        MONTO = @MONTO,
        DPI_ARRENDATARIO = @DPI_ARRENDATARIO,
        FOTO_DPI = @FOTO_DPI,
        ID_ESTADO = @ID_ESTADO,
        OBSERVACIONES = @OBSERVACIONES
    WHERE ID_ALQUILER_APTO = @ID_ALQUILER_APTO
END
GO