USE [TRZ6_CONDOMINIO]
GO

SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TRZ6_CAT_ESTADO'
ORDER BY ORDINAL_POSITION
GO

ALTER TABLE TRZ6_CAT_ESTADO
ADD MODIFICADO_POR VARCHAR(150) NULL,
    FE_MODIFICACION DATETIME NULL
	GO
	
SELECT * FROM TRZ6_CAT_ESTADO GO
select * from TRZ6_USUARIO go

EXEC sp_helpindex 'TRZ6_CAT_ESTADO'; GO

-- 1. Eliminar el índice único existente sobre CREADO_POR
ALTER TABLE TRZ6_CAT_ESTADO
DROP CONSTRAINT UQ__TRZ6_CAT__CC87E126C72E2FCA;
GO

-- 2. Crear un nuevo índice único sobre DESCRIPCION
ALTER TABLE TRZ6_CAT_ESTADO
ADD CONSTRAINT UQ_TRZ6_CAT_ESTADO_DESCRIPCION UNIQUE (DESCRIPCION);
GO


/********** LISTAR POR ID_ESTADO **********/
ALTER PROCEDURE SP_L_CAT_ESTADO_01  
    @ID_ESTADO INT  
AS  
BEGIN  
    SELECT  
        ID_ESTADO,
        DESCRIPCION,
        CONVERT(VARCHAR(10), FE_CREACION, 105) + ' ' +
        RIGHT('0' + CONVERT(VARCHAR(2), CASE WHEN DATEPART(HOUR, FE_CREACION) % 12 = 0 THEN 12 ELSE DATEPART(HOUR, FE_CREACION) % 12 END), 2) + ':' +
        RIGHT('0' + CONVERT(VARCHAR(2), DATEPART(MINUTE, FE_CREACION)), 2) + ' ' +
        CASE WHEN DATEPART(HOUR, FE_CREACION) >= 12 THEN 'PM' ELSE 'AM' END AS FE_CREACION,
        CREADO_POR,
        MODIFICADO_POR,
        CONVERT(VARCHAR(10), FE_MODIFICACION, 105) + ' ' +
        RIGHT('0' + CONVERT(VARCHAR(2), CASE WHEN DATEPART(HOUR, FE_MODIFICACION) % 12 = 0 THEN 12 ELSE DATEPART(HOUR, FE_MODIFICACION) % 12 END), 2) + ':' +
        RIGHT('0' + CONVERT(VARCHAR(2), DATEPART(MINUTE, FE_MODIFICACION)), 2) + ' ' +
        CASE WHEN DATEPART(HOUR, FE_MODIFICACION) >= 12 THEN 'PM' ELSE 'AM' END AS FE_MODIFICACION
    FROM TRZ6_CAT_ESTADO  
    WHERE ID_ESTADO = @ID_ESTADO
END  
GO

/********** LISTAR TODOS **********/
ALTER PROCEDURE SP_L_CAT_ESTADO_TODOS
AS
BEGIN
    SELECT
        ID_ESTADO,
        DESCRIPCION,
        CONVERT(VARCHAR(10), FE_CREACION, 105) + ' ' +
        RIGHT('0' + CONVERT(VARCHAR(2),
            CASE WHEN DATEPART(HOUR, FE_CREACION) % 12 = 0 THEN 12 ELSE DATEPART(HOUR, FE_CREACION) % 12 END
        ), 2) + ':' +
        RIGHT('0' + CONVERT(VARCHAR(2), DATEPART(MINUTE, FE_CREACION)), 2) + ' ' +
        CASE WHEN DATEPART(HOUR, FE_CREACION) >= 12 THEN 'PM' ELSE 'AM' END AS FE_CREACION,
        CREADO_POR,
        CONVERT(VARCHAR(10), FE_MODIFICACION, 105) + ' ' +
        RIGHT('0' + CONVERT(VARCHAR(2),
            CASE WHEN DATEPART(HOUR, FE_MODIFICACION) % 12 = 0 THEN 12 ELSE DATEPART(HOUR, FE_MODIFICACION) % 12 END
        ), 2) + ':' +
        RIGHT('0' + CONVERT(VARCHAR(2), DATEPART(MINUTE, FE_MODIFICACION)), 2) + ' ' +
        CASE WHEN DATEPART(HOUR, FE_MODIFICACION) >= 12 THEN 'PM' ELSE 'AM' END AS FE_MODIFICACION,
        MODIFICADO_POR
    FROM TRZ6_CAT_ESTADO
    ORDER BY ID_ESTADO DESC
END
GO


/********** OBTENER POR ID **********/
ALTER PROCEDURE SP_O_CAT_ESTADO_01
    @ID_ESTADO INT
AS
BEGIN
    SELECT
        ID_ESTADO,
        DESCRIPCION,
        CREADO_POR,
        CONVERT(VARCHAR(10), FE_CREACION, 105) + ' ' +
        RIGHT('0' + CONVERT(VARCHAR(2),
            CASE WHEN DATEPART(HOUR, FE_CREACION) % 12 = 0 THEN 12 ELSE DATEPART(HOUR, FE_CREACION) % 12 END
        ), 2) + ':' +
        RIGHT('0' + CONVERT(VARCHAR(2), DATEPART(MINUTE, FE_CREACION)), 2) + ' ' +
        CASE WHEN DATEPART(HOUR, FE_CREACION) >= 12 THEN 'PM' ELSE 'AM' END AS FE_CREACION,
        MODIFICADO_POR,
        CONVERT(VARCHAR(10), FE_MODIFICACION, 105) + ' ' +
        RIGHT('0' + CONVERT(VARCHAR(2),
            CASE WHEN DATEPART(HOUR, FE_MODIFICACION) % 12 = 0 THEN 12 ELSE DATEPART(HOUR, FE_MODIFICACION) % 12 END
        ), 2) + ':' +
        RIGHT('0' + CONVERT(VARCHAR(2), DATEPART(MINUTE, FE_MODIFICACION)), 2) + ' ' +
        CASE WHEN DATEPART(HOUR, FE_MODIFICACION) >= 12 THEN 'PM' ELSE 'AM' END AS FE_MODIFICACION
    FROM TRZ6_CAT_ESTADO
    WHERE ID_ESTADO = @ID_ESTADO
END
GO

/********** INSERTAR **********/
ALTER PROCEDURE SP_I_CAT_ESTADO_01
    @CREADO_POR VARCHAR(150),
    @DESCRIPCION VARCHAR(150)
AS
BEGIN
	DECLARE @FechaActual DATETIME = DATEADD(HOUR, -6, GETUTCDATE()); -- Hora Guatemala
    INSERT INTO TRZ6_CAT_ESTADO (
        CREADO_POR,
        DESCRIPCION,
        FE_CREACION,
        MODIFICADO_POR,
        FE_MODIFICACION
    )
    VALUES (
        @CREADO_POR,
        @DESCRIPCION,
        @FechaActual,
        @CREADO_POR,       -- Al inicio, quien crea también es quien modifica
        @FechaActual       -- Igualamos fecha de creación y modificación
    );
END
GO

ALTER PROCEDURE SP_I_CAT_ESTADO_01
    @CREADO_POR VARCHAR(150),
    @DESCRIPCION VARCHAR(150)
AS
BEGIN
	DECLARE @FechaActual DATETIME = DATEADD(HOUR, -6, GETUTCDATE()); -- Hora Guatemala
    -- Validar duplicidad
    IF EXISTS (SELECT 1 FROM TRZ6_CAT_ESTADO WHERE DESCRIPCION = @DESCRIPCION)
    BEGIN
        RAISERROR('La descripción ya existe. No se puede duplicar.', 16, 1);
        RETURN;
    END

    INSERT INTO TRZ6_CAT_ESTADO (
        CREADO_POR,
        DESCRIPCION,
        FE_CREACION,
        MODIFICADO_POR,
        FE_MODIFICACION
    )
    VALUES (
        @CREADO_POR,
        @DESCRIPCION,
        DATEADD(HOUR, -6, GETUTCDATE()), -- Hora local Guatemala
        @CREADO_POR,       -- Al inicio, quien crea también es quien modifica
        @FechaActual       -- Igualamos fecha de creación y modificación
    )
END
GO


/********** ACTUALIZAR **********/
ALTER PROCEDURE SP_U_CAT_ESTADO_01
    @ID_ESTADO INT,
    @CREADO_POR VARCHAR(150),
    @DESCRIPCION VARCHAR(150),
    @MODIFICADO_POR VARCHAR(150)
AS
BEGIN
	DECLARE @FechaActual DATETIME = DATEADD(HOUR, -6, GETUTCDATE()); -- Hora Guatemala
    -- Validar duplicidad excluyendo el mismo registro
    IF EXISTS (SELECT 1 FROM TRZ6_CAT_ESTADO WHERE DESCRIPCION = @DESCRIPCION AND ID_ESTADO != @ID_ESTADO)
    BEGIN
        RAISERROR('La descripción ya existe. No se puede duplicar.', 16, 1);
        RETURN;
    END

    UPDATE TRZ6_CAT_ESTADO
    SET
        CREADO_POR = @CREADO_POR,
        DESCRIPCION = @DESCRIPCION,
        MODIFICADO_POR = @MODIFICADO_POR,
        FE_MODIFICACION = @FechaActual
    WHERE ID_ESTADO = @ID_ESTADO;
END
GO



ALTER PROCEDURE SP_U_CAT_ESTADO_01
    @ID_ESTADO INT,
    @CREADO_POR VARCHAR(150),
    @DESCRIPCION VARCHAR(150),
    @MODIFICADO_POR VARCHAR(150)
AS
BEGIN
    UPDATE TRZ6_CAT_ESTADO
    SET
        CREADO_POR = @CREADO_POR,
        DESCRIPCION = @DESCRIPCION,
        MODIFICADO_POR = @MODIFICADO_POR,
        FE_MODIFICACION = DATEADD(HOUR, -6, GETUTCDATE()) -- Hora local Guatemala
    WHERE ID_ESTADO = @ID_ESTADO
END
GO

/********** ELIMINAR **********/
ALTER PROCEDURE SP_D_CAT_ESTADO_01
    @ID_ESTADO INT
AS
BEGIN
    DELETE FROM TRZ6_CAT_ESTADO
    WHERE ID_ESTADO = @ID_ESTADO
END
GO

