-- Listar todos los registro por Código Catgoría Estado
CREATE PROCEDURE SP_L_CAT_ESTADO_01
    @CODIGO VARCHAR(30)
AS
BEGIN
    SELECT
        ID_ESTADO,
        CODIGO,
        DESCRIPCION,
        FE_CREACION
    FROM TRZ6_CAT_ESTADO
    WHERE CODIGO = @CODIGO
END
GO

-- Obtener Categoría Estado por ID
CREATE PROCEDURE SP_O_CAT_ESTADO_01
    @ID_ESTADO INT
AS
BEGIN
    SELECT
        ID_ESTADO,
        CODIGO,
        DESCRIPCION,
        FE_CREACION
    FROM TRZ6_CAT_ESTADO
    WHERE ID_ESTADO = @ID_ESTADO
END
GO

-- Eliminar Categoría Estado por ID
CREATE PROCEDURE SP_D_CAT_ESTADO_01
    @ID_ESTADO INT
AS
BEGIN
    DELETE FROM TRZ6_CAT_ESTADO
    WHERE ID_ESTADO = @ID_ESTADO
END
GO

-- Insertar Categoría Estado
CREATE PROCEDURE SP_I_CAT_ESTADO_01
    @CODIGO VARCHAR(30),
    @DESCRIPCION VARCHAR(150)
AS
BEGIN
    INSERT INTO TRZ6_CAT_ESTADO (
        CODIGO,
        DESCRIPCION,
        FE_CREACION
    )
    VALUES (
        @CODIGO,
        @DESCRIPCION,
        SYSUTCDATETIME()
    )
END
GO

-- Update Registro Categoría Estado
CREATE PROCEDURE SP_U_CAT_ESTADO_01
    @ID_ESTADO INT,
    @CODIGO VARCHAR(30),
    @DESCRIPCION VARCHAR(150)
AS
BEGIN
    UPDATE TRZ6_CAT_ESTADO
    SET
        CODIGO = @CODIGO,
        DESCRIPCION = @DESCRIPCION
    WHERE ID_ESTADO = @ID_ESTADO
END
GO