SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TRZ6_CAT_TIPO_PAGO'
ORDER BY ORDINAL_POSITION
GO

-- Listar todos los registro por Código Categoria Tipo Pago
CREATE PROCEDURE SP_L_CAT_TIPO_PAGO_01
    @CODIGO VARCHAR(30)
AS
BEGIN
    SELECT
        ID_TIPO_PAGO,
        CODIGO,
        DESCRIPCION,
        FE_CREACION
    FROM TRZ6_CAT_TIPO_PAGO
    WHERE CODIGO = @CODIGO
END
GO

-- Obtener Categoría Tipo Pago por ID
CREATE PROCEDURE SP_O_CAT_TIPO_PAGO_01
    @ID_TIPO_PAGO INT
AS
BEGIN
    SELECT
        ID_TIPO_PAGO,
        CODIGO,
        DESCRIPCION,
        FE_CREACION
    FROM TRZ6_CAT_TIPO_PAGO
    WHERE ID_TIPO_PAGO = @ID_TIPO_PAGO
END
GO

-- Eliminar Categoría Tipo Pago por ID
CREATE PROCEDURE SP_D_CAT_TIPO_PAGO_01
    @ID_TIPO_PAGO INT
AS
BEGIN
    DELETE FROM TRZ6_CAT_TIPO_PAGO
    WHERE ID_TIPO_PAGO = @ID_TIPO_PAGO
END
GO

-- Insertar Categoría Tipo Pago
CREATE PROCEDURE SP_I_CAT_TIPO_PAGO_01
    @CODIGO VARCHAR(30),
    @DESCRIPCION VARCHAR(150)
AS
BEGIN
    INSERT INTO TRZ6_CAT_TIPO_PAGO (
        CODIGO,
        DESCRIPCION,
        FE_CREACION
    )
    VALUES (
        @CODIGO,
        @DESCRIPCION,
        SYSUTCDATETIME()
    )
END
GO

-- Update Registro Categoría Tipo Pago
CREATE PROCEDURE SP_U_CAT_TIPO_PAGO_01
    @ID_TIPO_PAGO INT,
    @CODIGO VARCHAR(30),
    @DESCRIPCION VARCHAR(150)
AS
BEGIN
    UPDATE TRZ6_CAT_TIPO_PAGO
    SET
        CODIGO = @CODIGO,
        DESCRIPCION = @DESCRIPCION
    WHERE ID_TIPO_PAGO = @ID_TIPO_PAGO
END
GO