SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TRZ6_CONT_PRIN_AGUA'
ORDER BY ORDINAL_POSITION
GO

SELECT * FROM TRZ6_CONT_PRIN_AGUA GO

-- Listar registros por ID_PROVEEDOR
CREATE PROCEDURE SP_L_CONT_PRIN_AGUA_01
    @ID_PROVEEDOR INT
AS
BEGIN
    SELECT
        ID_CONT_PRIN_AGUA,
        ID_PROVEEDOR,
        ID_SERVICIO,
        FECHA_INGRESO,
        NUMERO_BOLETA,
        TOTAL_M3,
        MONTO,
        COSTO_XM3,
        LECTURA_INICIAL,
        LECTURA_FINAL,
        MTS_CUBICOS,
        INVENTARIO_FINAL_M3,
        OBSERVACIONES,
        FE_CREACION
    FROM TRZ6_CONT_PRIN_AGUA
    WHERE ID_PROVEEDOR = @ID_PROVEEDOR
    ORDER BY ID_CONT_PRIN_AGUA DESC
END
GO

-- Obtener registro por ID_CONT_PRIN_AGUA
CREATE PROCEDURE SP_O_CONT_PRIN_AGUA_01
    @ID_CONT_PRIN_AGUA INT
AS
BEGIN
    SELECT
        ID_CONT_PRIN_AGUA,
        ID_PROVEEDOR,
        ID_SERVICIO,
        FECHA_INGRESO,
        NUMERO_BOLETA,
        TOTAL_M3,
        MONTO,
        COSTO_XM3,
        LECTURA_INICIAL,
        LECTURA_FINAL,
        MTS_CUBICOS,
        INVENTARIO_FINAL_M3,
        OBSERVACIONES,
        FOTO_BOLETA,
        FE_CREACION
    FROM TRZ6_CONT_PRIN_AGUA
    WHERE ID_CONT_PRIN_AGUA = @ID_CONT_PRIN_AGUA
END
GO

-- Eliminar registro por ID_CONT_PRIN_AGUA
CREATE PROCEDURE SP_D_CONT_PRIN_AGUA_01
    @ID_CONT_PRIN_AGUA INT
AS
BEGIN
    DELETE FROM TRZ6_CONT_PRIN_AGUA
    WHERE ID_CONT_PRIN_AGUA = @ID_CONT_PRIN_AGUA
END
GO

-- Insertar nuevo registro con cálculo automático
CREATE PROCEDURE SP_I_CONT_PRIN_AGUA_01
    @ID_PROVEEDOR INT,
    @ID_SERVICIO INT,
    @FECHA_INGRESO DATE,
    @NUMERO_BOLETA VARCHAR(50),
    @MONTO DECIMAL(18,2),
    @LECTURA_INICIAL DECIMAL(18,2),
    @LECTURA_FINAL DECIMAL(18,2),
    @INVENTARIO_FINAL_M3 DECIMAL(18,2),
    @OBSERVACIONES VARCHAR(300),
    @FOTO_BOLETA VARBINARY(MAX)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @TOTAL_M3 DECIMAL(18,2) = @LECTURA_FINAL - @LECTURA_INICIAL;
    DECLARE @COSTO_XM3 DECIMAL(18,4) = CASE 
        WHEN @TOTAL_M3 <> 0 THEN @MONTO / @TOTAL_M3 
        ELSE 0 
    END;

    INSERT INTO TRZ6_CONT_PRIN_AGUA (
        ID_PROVEEDOR,
        ID_SERVICIO,
        FECHA_INGRESO,
        NUMERO_BOLETA,
        TOTAL_M3,
        MONTO,
        COSTO_XM3,
        LECTURA_INICIAL,
        LECTURA_FINAL,
        INVENTARIO_FINAL_M3,
        OBSERVACIONES,
        FOTO_BOLETA,
        FE_CREACION
    )
    VALUES (
        @ID_PROVEEDOR,
        @ID_SERVICIO,
        @FECHA_INGRESO,
        @NUMERO_BOLETA,
        @TOTAL_M3,
        @MONTO,
        @COSTO_XM3,
        @LECTURA_INICIAL,
        @LECTURA_FINAL,
        @INVENTARIO_FINAL_M3,
        @OBSERVACIONES,
        @FOTO_BOLETA,
        SYSUTCDATETIME()
    )
END
GO

-- Actualizar registro con cálculo automático
CREATE PROCEDURE SP_U_CONT_PRIN_AGUA_01
    @ID_CONT_PRIN_AGUA INT,
    @ID_PROVEEDOR INT,
    @ID_SERVICIO INT,
    @FECHA_INGRESO DATE,
    @NUMERO_BOLETA VARCHAR(50),
    @MONTO DECIMAL(18,2),
    @LECTURA_INICIAL DECIMAL(18,2),
    @LECTURA_FINAL DECIMAL(18,2),
    @INVENTARIO_FINAL_M3 DECIMAL(18,2),
    @OBSERVACIONES VARCHAR(300),
    @FOTO_BOLETA VARBINARY(MAX)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @TOTAL_M3 DECIMAL(18,2) = @LECTURA_FINAL - @LECTURA_INICIAL;
    DECLARE @COSTO_XM3 DECIMAL(18,4) = CASE 
        WHEN @TOTAL_M3 <> 0 THEN @MONTO / @TOTAL_M3 
        ELSE 0 
    END;

    UPDATE TRZ6_CONT_PRIN_AGUA
    SET
        ID_PROVEEDOR = @ID_PROVEEDOR,
        ID_SERVICIO = @ID_SERVICIO,
        FECHA_INGRESO = @FECHA_INGRESO,
        NUMERO_BOLETA = @NUMERO_BOLETA,
        TOTAL_M3 = @TOTAL_M3,
        MONTO = @MONTO,
        COSTO_XM3 = @COSTO_XM3,
        LECTURA_INICIAL = @LECTURA_INICIAL,
        LECTURA_FINAL = @LECTURA_FINAL,
        INVENTARIO_FINAL_M3 = @INVENTARIO_FINAL_M3,
        OBSERVACIONES = @OBSERVACIONES,
        FOTO_BOLETA = @FOTO_BOLETA
    WHERE ID_CONT_PRIN_AGUA = @ID_CONT_PRIN_AGUA
END
GO