SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TRZ6_INCIDENCIA'
ORDER BY ORDINAL_POSITION
GO

SELECT * FROM TRZ6_INCIDENCIA GO

-- Listar registros por ID_APTO
-- ❗Nota: No se incluye FOTO_EVIDENCIA para que sea más liviano.
CREATE PROCEDURE SP_L_INCIDENCIA_01
    @ID_APTO INT
AS
BEGIN
    SELECT
        ID_INCIDENCIA,
        ID_APTO,
        ID_REPORTADO_POR,
        FE_REPORTE,
        DESCRIPCION_GENERAL,
        FE_CREACION
    FROM TRZ6_INCIDENCIA
    WHERE ID_APTO = @ID_APTO
    ORDER BY ID_INCIDENCIA DESC
END
GO

-- Obtener incidencia por ID_INCIDENCIA
CREATE PROCEDURE SP_O_INCIDENCIA_01
    @ID_INCIDENCIA INT
AS
BEGIN
    SELECT
        ID_INCIDENCIA,
        ID_APTO,
        ID_REPORTADO_POR,
        FE_REPORTE,
        DESCRIPCION_GENERAL,
        FOTO_EVIDENCIA,
        FE_CREACION
    FROM TRZ6_INCIDENCIA
    WHERE ID_INCIDENCIA = @ID_INCIDENCIA
END
GO

-- Eliminar incidencia por ID_INCIDENCIA
CREATE PROCEDURE SP_D_INCIDENCIA_01
    @ID_INCIDENCIA INT
AS
BEGIN
    DELETE FROM TRZ6_INCIDENCIA
    WHERE ID_INCIDENCIA = @ID_INCIDENCIA
END
GO

-- Insertar nueva incidencia
CREATE PROCEDURE SP_I_INCIDENCIA_01
    @ID_APTO INT,
    @ID_REPORTADO_POR INT,
    @FE_REPORTE DATE,
    @DESCRIPCION_GENERAL VARCHAR(300),
    @FOTO_EVIDENCIA VARBINARY(MAX)
AS
BEGIN
    INSERT INTO TRZ6_INCIDENCIA (
        ID_APTO,
        ID_REPORTADO_POR,
        FE_REPORTE,
        DESCRIPCION_GENERAL,
        FOTO_EVIDENCIA,
        FE_CREACION
    )
    VALUES (
        @ID_APTO,
        @ID_REPORTADO_POR,
        @FE_REPORTE,
        @DESCRIPCION_GENERAL,
        @FOTO_EVIDENCIA,
        SYSUTCDATETIME()
    )
END
GO

-- Actualizar incidencia por ID_INCIDENCIA
CREATE PROCEDURE SP_U_INCIDENCIA_01
    @ID_INCIDENCIA INT,
    @ID_APTO INT,
    @ID_REPORTADO_POR INT,
    @FE_REPORTE DATE,
    @DESCRIPCION_GENERAL VARCHAR(300),
    @FOTO_EVIDENCIA VARBINARY(MAX)
AS
BEGIN
    UPDATE TRZ6_INCIDENCIA
    SET
        ID_APTO = @ID_APTO,
        ID_REPORTADO_POR = @ID_REPORTADO_POR,
        FE_REPORTE = @FE_REPORTE,
        DESCRIPCION_GENERAL = @DESCRIPCION_GENERAL,
        FOTO_EVIDENCIA = @FOTO_EVIDENCIA
    WHERE ID_INCIDENCIA = @ID_INCIDENCIA
END
GO