CREATE OR ALTER PROCEDURE SP_U_MENU_01
@ID_DETMENU INT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE TRZ6_MENU_DETALLE
    SET PERMISO_DETMENU = 'SI',
        FEC_ACTUALIZACION = GETDATE()
    WHERE ID_DETMENU = @ID_DETMENU;
END
GO

CREATE OR ALTER PROCEDURE SP_U_MENU_02
@ID_DETMENU INT
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE TRZ6_MENU_DETALLE
    SET PERMISO_DETMENU = 'NO',
        FEC_ACTUALIZACION = GETDATE()
    WHERE ID_DETMENU = @ID_DETMENU;
END
GO