SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TRZ6_PROVEEDOR'
ORDER BY ORDINAL_POSITION
GO

SELECT * FROM TRZ6_PROVEEDOR GO

-- Listar proveedores por servicio (ID_SERVICIO)
CREATE PROCEDURE SP_L_PROVEEDOR_01
    @ID_SERVICIO INT
AS
BEGIN
    SELECT
        ID_PROVEEDOR,
        ID_SERVICIO,
        NIT_PROVEEDOR,
        RAZON_SOCIAL,
        TELEFONO,
        CORREO,
        NOM_CONTACTO,
        CEL_CONTACTO,
        CORREO_CONTACTO,
        DIRECCION,
        UBICACION_MAPA,
        FE_CREACION
    FROM TRZ6_PROVEEDOR
    WHERE ID_SERVICIO = @ID_SERVICIO
    ORDER BY ID_PROVEEDOR DESC
END
GO

-- Obtener proveedor por ID
CREATE PROCEDURE SP_O_PROVEEDOR_01
    @ID_PROVEEDOR INT
AS
BEGIN
    SELECT
        ID_PROVEEDOR,
        ID_SERVICIO,
        NIT_PROVEEDOR,
        RAZON_SOCIAL,
        TELEFONO,
        CORREO,
        NOM_CONTACTO,
        CEL_CONTACTO,
        CORREO_CONTACTO,
        DIRECCION,
        UBICACION_MAPA,
        FE_CREACION
    FROM TRZ6_PROVEEDOR
    WHERE ID_PROVEEDOR = @ID_PROVEEDOR
END
GO

-- Eliminar proveedor por ID
CREATE PROCEDURE SP_D_PROVEEDOR_01
    @ID_PROVEEDOR INT
AS
BEGIN
    DELETE FROM TRZ6_PROVEEDOR
    WHERE ID_PROVEEDOR = @ID_PROVEEDOR
END
GO

-- Insertar nuevo proveedor
CREATE PROCEDURE SP_I_PROVEEDOR_01
    @ID_SERVICIO INT,
    @NIT_PROVEEDOR VARCHAR(30),
    @RAZON_SOCIAL VARCHAR(150),
    @TELEFONO VARCHAR(30),
    @CORREO VARCHAR(100),
    @NOM_CONTACTO VARCHAR(100),
    @CEL_CONTACTO VARCHAR(30),
    @CORREO_CONTACTO VARCHAR(100),
    @DIRECCION VARCHAR(300),
    @UBICACION_MAPA VARCHAR(500)
AS
BEGIN
    INSERT INTO TRZ6_PROVEEDOR (
        ID_SERVICIO,
        NIT_PROVEEDOR,
        RAZON_SOCIAL,
        TELEFONO,
        CORREO,
        NOM_CONTACTO,
        CEL_CONTACTO,
        CORREO_CONTACTO,
        DIRECCION,
        UBICACION_MAPA,
        FE_CREACION
    )
    VALUES (
        @ID_SERVICIO,
        @NIT_PROVEEDOR,
        @RAZON_SOCIAL,
        @TELEFONO,
        @CORREO,
        @NOM_CONTACTO,
        @CEL_CONTACTO,
        @CORREO_CONTACTO,
        @DIRECCION,
        @UBICACION_MAPA,
        SYSUTCDATETIME()
    )
END
GO

-- Actualizar proveedor
CREATE PROCEDURE SP_U_PROVEEDOR_01
    @ID_PROVEEDOR INT,
    @ID_SERVICIO INT,
    @NIT_PROVEEDOR VARCHAR(30),
    @RAZON_SOCIAL VARCHAR(150),
    @TELEFONO VARCHAR(30),
    @CORREO VARCHAR(100),
    @NOM_CONTACTO VARCHAR(100),
    @CEL_CONTACTO VARCHAR(30),
    @CORREO_CONTACTO VARCHAR(100),
    @DIRECCION VARCHAR(300),
    @UBICACION_MAPA VARCHAR(500)
AS
BEGIN
    UPDATE TRZ6_PROVEEDOR
    SET
        ID_SERVICIO = @ID_SERVICIO,
        NIT_PROVEEDOR = @NIT_PROVEEDOR,
        RAZON_SOCIAL = @RAZON_SOCIAL,
        TELEFONO = @TELEFONO,
        CORREO = @CORREO,
        NOM_CONTACTO = @NOM_CONTACTO,
        CEL_CONTACTO = @CEL_CONTACTO,
        CORREO_CONTACTO = @CORREO_CONTACTO,
        DIRECCION = @DIRECCION,
        UBICACION_MAPA = @UBICACION_MAPA
    WHERE ID_PROVEEDOR = @ID_PROVEEDOR
END
GO