SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TRZ6_USUARIO'
ORDER BY ORDINAL_POSITION
GO

SELECT * FROM TRZ6_USUARIO GO

-- Listar usuarios por estado (ID_ESTADO)
CREATE PROCEDURE SP_L_USUARIO_01
    @ID_ESTADO INT
AS
BEGIN
    SELECT
        ID_USER,
        ID_APTO,
        EMAIL,
        NOMBRES,
        APELLIDOS,
        DPI,
        TELEFONO,
        ID_ESTADO,
        FE_CREACION,
        ROL_ID
    FROM TRZ6_USUARIO
    WHERE ID_ESTADO = @ID_ESTADO
    ORDER BY ID_USER DESC
END
GO

-- Obtener usuario por ID
CREATE PROCEDURE SP_O_USUARIO_01
    @ID_USER INT
AS
BEGIN
    SELECT
        ID_USER,
        ID_APTO,
        EMAIL,
        NOMBRES,
        APELLIDOS,
        DPI,
        TELEFONO,
        PASSWORD,
        FOTO_PERFIL,
        ID_ESTADO,
        FE_CREACION,
        ROL_ID
    FROM TRZ6_USUARIO
    WHERE ID_USER = @ID_USER
END
GO

-- Eliminar usuario por ID
CREATE PROCEDURE SP_D_USUARIO_01
    @ID_USER INT
AS
BEGIN
    DELETE FROM TRZ6_USUARIO
    WHERE ID_USER = @ID_USER
END
GO

-- Insertar nuevo usuario
CREATE PROCEDURE SP_I_USUARIO_01
    @ID_APTO INT,
    @EMAIL VARCHAR(150),
    @NOMBRES VARCHAR(150),
    @APELLIDOS VARCHAR(150),
    @DPI VARCHAR(50),
    @TELEFONO VARCHAR(50),
    @PASSWORD VARCHAR(150),
    @FOTO_PERFIL VARBINARY(MAX),
    @ID_ESTADO INT,
    @ROL_ID INT
AS
BEGIN
    INSERT INTO TRZ6_USUARIO (
        ID_APTO,
        EMAIL,
        NOMBRES,
        APELLIDOS,
        DPI,
        TELEFONO,
        PASSWORD,
        FOTO_PERFIL,
        ID_ESTADO,
        FE_CREACION,
        ROL_ID
    )
    VALUES (
        @ID_APTO,
        @EMAIL,
        @NOMBRES,
        @APELLIDOS,
        @DPI,
        @TELEFONO,
        @PASSWORD,
        @FOTO_PERFIL,
        @ID_ESTADO,
        SYSUTCDATETIME(),
        @ROL_ID
    )
END
GO

-- Actualizar usuario por ID
CREATE PROCEDURE SP_U_USUARIO_01
    @ID_USER INT,
    @ID_APTO INT,
    @EMAIL VARCHAR(150),
    @NOMBRES VARCHAR(150),
    @APELLIDOS VARCHAR(150),
    @DPI VARCHAR(50),
    @TELEFONO VARCHAR(50),
    @PASSWORD VARCHAR(150),
    @FOTO_PERFIL VARBINARY(MAX),
    @ID_ESTADO INT,
    @ROL_ID INT
AS
BEGIN
    UPDATE TRZ6_USUARIO
    SET
        ID_APTO = @ID_APTO,
        EMAIL = @EMAIL,
        NOMBRES = @NOMBRES,
        APELLIDOS = @APELLIDOS,
        DPI = @DPI,
        TELEFONO = @TELEFONO,
        PASSWORD = @PASSWORD,
        FOTO_PERFIL = @FOTO_PERFIL,
        ID_ESTADO = @ID_ESTADO,
        ROL_ID = @ROL_ID
    WHERE ID_USER = @ID_USER
END
GO

-- ACCESO DE USUARIO
CREATE PROCEDURE SP_L_USUARIO_02
    @EMAIL VARCHAR(150),
    @PASSWORD VARCHAR(150)
AS
BEGIN
    SELECT
        ID_USER,
        NOMBRES,
        APELLIDOS,
        ROL_ID
    FROM TRZ6_USUARIO
    WHERE
        EMAIL = @EMAIL
        AND PASSWORD = @PASSWORD
        AND ID_ESTADO = 1  -- (opcional: solo usuarios activos)
END
GO

-- CAMBIO DE CONTRASE�A
CREATE PROCEDURE SP_U_USUARIO_02
    @ID_USER INT,
    @PASSWORD VARCHAR(150)
AS
BEGIN
    UPDATE TRZ6_USUARIO
    SET
        PASSWORD = @PASSWORD
    WHERE
        ID_USER = @ID_USER
END
GO