-- Listar todos los registro por Usuario
CREATE PROCEDURE SP_L_AUTO_INGRESO_01
    @ID_USER INT
AS
BEGIN
    SELECT
        ID_AUTO_INGRESO,
        ID_USER,
        NOMBRES_VISITANTE,
        APELLIDOS_VISITANTE,
        DPI_VISITANTE,
        FE_VISITA,
        TOT_ADULTOS,
        TOT_JOVENES,
        TOT_MENORES,
        FE_CREACION
    FROM TRZ6_AUTO_INGRESO
    WHERE ID_USER = @ID_USER
END
GO

-- Obtener autorización de ingreso por ID
CREATE PROCEDURE SP_O_AUTO_INGRESO_01
    @ID_AUTO_INGRESO INT
AS
BEGIN
    SELECT
        ID_AUTO_INGRESO,
        ID_USER,
        NOMBRES_VISITANTE,
        APELLIDOS_VISITANTE,
        DPI_VISITANTE,
        FE_VISITA,
        TOT_ADULTOS,
        TOT_JOVENES,
        TOT_MENORES,
        FOTO_DPI_PRINCIPAL,
        FE_CREACION
    FROM TRZ6_AUTO_INGRESO
    WHERE ID_AUTO_INGRESO = @ID_AUTO_INGRESO
END
GO

-- Eliminar autorización de ingreso por ID
CREATE PROCEDURE SP_D_AUTO_INGRESO_01
    @ID_AUTO_INGRESO INT
AS
BEGIN
    DELETE FROM TRZ6_AUTO_INGRESO
    WHERE ID_AUTO_INGRESO = @ID_AUTO_INGRESO
END
GO

-- Insertar nueva autorización
CREATE PROCEDURE SP_I_AUTO_INGRESO_01
    @ID_USER INT,
    @NOMBRES_VISITANTE VARCHAR(150),
    @APELLIDOS_VISITANTE VARCHAR(150),
    @DPI_VISITANTE VARCHAR(50),
    @FE_VISITA DATE,
    @TOT_ADULTOS INT,
    @TOT_JOVENES INT,
    @TOT_MENORES INT,
    @FOTO_DPI_PRINCIPAL VARBINARY(MAX) = NULL
AS
BEGIN
    INSERT INTO TRZ6_AUTO_INGRESO (
        ID_USER,
        NOMBRES_VISITANTE,
        APELLIDOS_VISITANTE,
        DPI_VISITANTE,
        FE_VISITA,
        TOT_ADULTOS,
        TOT_JOVENES,
        TOT_MENORES,
        FOTO_DPI_PRINCIPAL,
        FE_CREACION
    )
    VALUES (
        @ID_USER,
        @NOMBRES_VISITANTE,
        @APELLIDOS_VISITANTE,
        @DPI_VISITANTE,
        @FE_VISITA,
        @TOT_ADULTOS,
        @TOT_JOVENES,
        @TOT_MENORES,
        @FOTO_DPI_PRINCIPAL,
        SYSUTCDATETIME()
    )
END
GO

-- Update registro
CREATE PROCEDURE SP_U_AUTO_INGRESO_01
    @ID_AUTO_INGRESO INT,
    @ID_USER INT,
    @NOMBRES_VISITANTE VARCHAR(150),
    @APELLIDOS_VISITANTE VARCHAR(150),
    @DPI_VISITANTE VARCHAR(50),
    @FE_VISITA DATE,
    @TOT_ADULTOS INT,
    @TOT_JOVENES INT,
    @TOT_MENORES INT,
    @FOTO_DPI_PRINCIPAL VARBINARY(MAX) = NULL
AS
BEGIN
    UPDATE TRZ6_AUTO_INGRESO
    SET
        ID_USER = @ID_USER,
        NOMBRES_VISITANTE = @NOMBRES_VISITANTE,
        APELLIDOS_VISITANTE = @APELLIDOS_VISITANTE,
        DPI_VISITANTE = @DPI_VISITANTE,
        FE_VISITA = @FE_VISITA,
        TOT_ADULTOS = @TOT_ADULTOS,
        TOT_JOVENES = @TOT_JOVENES,
        TOT_MENORES = @TOT_MENORES,
        FOTO_DPI_PRINCIPAL = @FOTO_DPI_PRINCIPAL
    WHERE ID_AUTO_INGRESO = @ID_AUTO_INGRESO
END
GO