SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TRZ6_CAT_SERVICIO'
ORDER BY ORDINAL_POSITION
GO

-- Listar todos los registro por Código Categoria Servicio
CREATE PROCEDURE SP_L_CAT_SERVICIO_01
    @CODIGO VARCHAR(30)
AS
BEGIN
    SELECT
        ID_SERVICIO,
        CODIGO,
        DESCRIPCION,
        FE_CREACION
    FROM TRZ6_CAT_SERVICIO
    WHERE CODIGO = @CODIGO
END
GO

-- Obtener Categoría Servicio por ID
CREATE PROCEDURE SP_O_CAT_SERVICIO_01
    @ID_SERVICIO INT
AS
BEGIN
    SELECT
        ID_SERVICIO,
        CODIGO,
        DESCRIPCION,
        FE_CREACION
    FROM TRZ6_CAT_SERVICIO
    WHERE ID_SERVICIO = @ID_SERVICIO
END
GO

-- Eliminar Categoría Servicio por ID
CREATE PROCEDURE SP_D_CAT_SERVICIO_01
    @ID_SERVICIO INT
AS
BEGIN
    DELETE FROM TRZ6_CAT_SERVICIO
    WHERE ID_SERVICIO = @ID_SERVICIO
END
GO

-- Insertar Categoría Servicio
CREATE PROCEDURE SP_I_CAT_SERVICIO_01
    @CODIGO VARCHAR(30),
    @DESCRIPCION VARCHAR(150)
AS
BEGIN
    INSERT INTO TRZ6_CAT_SERVICIO (
        CODIGO,
        DESCRIPCION,
        FE_CREACION
    )
    VALUES (
        @CODIGO,
        @DESCRIPCION,
        SYSUTCDATETIME()
    )
END
GO

-- Update Registro Categoría Servicio
CREATE PROCEDURE SP_U_CAT_SERVICIO_01
    @ID_SERVICIO INT,
    @CODIGO VARCHAR(30),
    @DESCRIPCION VARCHAR(150)
AS
BEGIN
    UPDATE TRZ6_CAT_SERVICIO
    SET
        CODIGO = @CODIGO,
        DESCRIPCION = @DESCRIPCION
    WHERE ID_SERVICIO = @ID_SERVICIO
END
GO