SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TRZ6_CONT_APTO_AGUA'
ORDER BY ORDINAL_POSITION
GO

SELECT * FROM TRZ6_CONT_APTO_AGUA GO

-- Listar por ID_CONT_APTO_AGUA
CREATE PROCEDURE SP_L_CONT_APTO_AGUA_01
    @ID_APTO INT
AS
BEGIN
    SELECT
        ID_CONT_APTO_AGUA,
        ID_APTO,
        ID_CONT_PRIN_AGUA,
        FE_DESDE,
        FE_HASTA,
        RESERVA_EN_CISTERNA_M3,
        TOTAL_M3,
        TOTAL_A_CANCELAR,
        LECTURA_INICIAL,
        LECTURA_FINAL,
        DIF_LECTURA,
        SALDO_ANTERIOR,
        OBSERVACIONES,
        FE_CREACION
    FROM TRZ6_CONT_APTO_AGUA
    WHERE ID_APTO = @ID_APTO
    ORDER BY ID_CONT_APTO_AGUA DESC
END
GO

-- Obtener por ID_CONT_APTO_AGUA
CREATE PROCEDURE SP_O_CONT_APTO_AGUA_01
    @ID_CONT_APTO_AGUA INT
AS
BEGIN
    SELECT
        ID_CONT_APTO_AGUA,
        ID_APTO,
        ID_CONT_PRIN_AGUA,
        FE_DESDE,
        FE_HASTA,
        RESERVA_EN_CISTERNA_M3,
        TOTAL_M3,
        TOTAL_A_CANCELAR,
        LECTURA_INICIAL,
        LECTURA_FINAL,
        DIF_LECTURA,
        SALDO_ANTERIOR,
        OBSERVACIONES,
        FE_CREACION
    FROM TRZ6_CONT_APTO_AGUA
    WHERE ID_CONT_APTO_AGUA = @ID_CONT_APTO_AGUA
END
GO

-- Eliminar por ID_CONT_APTO_AGUA
CREATE PROCEDURE SP_D_CONT_APTO_AGUA_01
    @ID_CONT_APTO_AGUA INT
AS
BEGIN
    DELETE FROM TRZ6_CONT_APTO_AGUA
    WHERE ID_CONT_APTO_AGUA = @ID_CONT_APTO_AGUA
END
GO

-- Insertar nuevo registro con cálculo automático
CREATE PROCEDURE SP_I_CONT_APTO_AGUA_01
    @ID_APTO INT,
    @ID_CONT_PRIN_AGUA INT,
    @FE_DESDE DATE,
    @FE_HASTA DATE,
    @RESERVA_EN_CISTERNA_M3 DECIMAL(10,2),
    @LECTURA_INICIAL DECIMAL(10,2),
    @LECTURA_FINAL DECIMAL(10,2),
    @SALDO_ANTERIOR DECIMAL(10,2),
    @OBSERVACIONES VARCHAR(300)
AS
BEGIN
    SET NOCOUNT ON;

    -- Cálculos automáticos
    DECLARE @COSTO_XM3 DECIMAL(18,4) = (
        SELECT TOP 1 COSTO_XM3
        FROM dbo.TRZ6_CONT_PRIN_AGUA
        WHERE ID_CONT_PRIN_AGUA = @ID_CONT_PRIN_AGUA
    );

    DECLARE @TOTAL_M3 DECIMAL(18,2) = @LECTURA_FINAL - @LECTURA_INICIAL;
    DECLARE @TOTAL_A_CANCELAR DECIMAL(18,2) = @TOTAL_M3 * @COSTO_XM3;

    -- Inserción (sin DIF_LECTURA)
    INSERT INTO TRZ6_CONT_APTO_AGUA (
        ID_APTO,
        ID_CONT_PRIN_AGUA,
        FE_DESDE,
        FE_HASTA,
        RESERVA_EN_CISTERNA_M3,
        TOTAL_M3,
        TOTAL_A_CANCELAR,
        LECTURA_INICIAL,
        LECTURA_FINAL,
        SALDO_ANTERIOR,
        OBSERVACIONES,
        FE_CREACION
    )
    VALUES (
        @ID_APTO,
        @ID_CONT_PRIN_AGUA,
        @FE_DESDE,
        @FE_HASTA,
        @RESERVA_EN_CISTERNA_M3,
        @TOTAL_M3,
        @TOTAL_A_CANCELAR,
        @LECTURA_INICIAL,
        @LECTURA_FINAL,
        @SALDO_ANTERIOR,
        @OBSERVACIONES,
        SYSUTCDATETIME()
    )
END
GO

-- Actualizar Contador Apatamento Propietario por ID_APTO
CREATE PROCEDURE SP_U_CONT_APTO_AGUA_01
    @ID_CONT_APTO_AGUA INT,
    @ID_APTO INT,
    @ID_CONT_PRIN_AGUA INT,
    @FE_DESDE DATE,
    @FE_HASTA DATE,
    @RESERVA_EN_CISTERNA_M3 DECIMAL(10,2),
    @LECTURA_INICIAL DECIMAL(10,2),
    @LECTURA_FINAL DECIMAL(10,2),
    @SALDO_ANTERIOR DECIMAL(10,2),
    @OBSERVACIONES VARCHAR(300)
AS
BEGIN
    SET NOCOUNT ON;

    -- Obtener costo por m³ del contador principal
    DECLARE @COSTO_XM3 DECIMAL(18,4) = (
        SELECT TOP 1 COSTO_XM3
        FROM dbo.TRZ6_CONT_PRIN_AGUA
        WHERE ID_CONT_PRIN_AGUA = @ID_CONT_PRIN_AGUA
    );

    -- Total m³ y total a cancelar
    DECLARE @TOTAL_M3 DECIMAL(18,2) = @LECTURA_FINAL - @LECTURA_INICIAL;
    DECLARE @TOTAL_A_CANCELAR DECIMAL(18,2) = @TOTAL_M3 * @COSTO_XM3;

    -- Actualización del registro
    UPDATE TRZ6_CONT_APTO_AGUA
    SET
        ID_APTO = @ID_APTO,
        ID_CONT_PRIN_AGUA = @ID_CONT_PRIN_AGUA,
        FE_DESDE = @FE_DESDE,
        FE_HASTA = @FE_HASTA,
        RESERVA_EN_CISTERNA_M3 = @RESERVA_EN_CISTERNA_M3,
        TOTAL_M3 = @TOTAL_M3,
        TOTAL_A_CANCELAR = @TOTAL_A_CANCELAR,
        LECTURA_INICIAL = @LECTURA_INICIAL,
        LECTURA_FINAL = @LECTURA_FINAL,
        SALDO_ANTERIOR = @SALDO_ANTERIOR,
        OBSERVACIONES = @OBSERVACIONES
    WHERE ID_CONT_APTO_AGUA = @ID_CONT_APTO_AGUA
END
GO