SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TRZ6_PAGO_MANTTO'
ORDER BY ORDINAL_POSITION
GO

SELECT * FROM TRZ6_PAGO_MANTTO GO

-- Listar pagos por usuario (ID_USER)
-- 🔹 Se excluye COMPROBANTE para que sea más ligero (útil en listados generales).
CREATE PROCEDURE SP_L_PAGO_MANTTO_01
    @ID_USER INT
AS
BEGIN
    SELECT
        ID_PAGO_MANTTO,
        ID_USER,
        ID_TIPO_PAGO,
        MONTO,
        FE_PAGO,
        ID_ESTADO,
        FE_CREACION
    FROM TRZ6_PAGO_MANTTO
    WHERE ID_USER = @ID_USER
    ORDER BY ID_PAGO_MANTTO DESC
END
GO

-- Obtener un pago por ID_PAGO_MANTTO
CREATE PROCEDURE SP_O_PAGO_MANTTO_01
    @ID_PAGO_MANTTO INT
AS
BEGIN
    SELECT
        ID_PAGO_MANTTO,
        ID_USER,
        ID_TIPO_PAGO,
        MONTO,
        FE_PAGO,
        ID_ESTADO,
        COMPROBANTE,
        FE_CREACION
    FROM TRZ6_PAGO_MANTTO
    WHERE ID_PAGO_MANTTO = @ID_PAGO_MANTTO
END
GO

-- Eliminar pago por ID_PAGO_MANTTO
CREATE PROCEDURE SP_D_PAGO_MANTTO_01
    @ID_PAGO_MANTTO INT
AS
BEGIN
    DELETE FROM TRZ6_PAGO_MANTTO
    WHERE ID_PAGO_MANTTO = @ID_PAGO_MANTTO
END
GO

-- Insertar nuevo pago
CREATE PROCEDURE SP_I_PAGO_MANTTO_01
    @ID_USER INT,
    @ID_TIPO_PAGO INT,
    @MONTO DECIMAL(18,2),
    @FE_PAGO DATE,
    @ID_ESTADO INT,
    @COMPROBANTE VARBINARY(MAX)
AS
BEGIN
    INSERT INTO TRZ6_PAGO_MANTTO (
        ID_USER,
        ID_TIPO_PAGO,
        MONTO,
        FE_PAGO,
        ID_ESTADO,
        COMPROBANTE,
        FE_CREACION
    )
    VALUES (
        @ID_USER,
        @ID_TIPO_PAGO,
        @MONTO,
        @FE_PAGO,
        @ID_ESTADO,
        @COMPROBANTE,
        SYSUTCDATETIME()
    )
END
GO

-- Actualizar pago por ID_PAGO_MANTTO
CREATE PROCEDURE SP_U_PAGO_MANTTO_01
    @ID_PAGO_MANTTO INT,
    @ID_USER INT,
    @ID_TIPO_PAGO INT,
    @MONTO DECIMAL(18,2),
    @FE_PAGO DATE,
    @ID_ESTADO INT,
    @COMPROBANTE VARBINARY(MAX)
AS
BEGIN
    UPDATE TRZ6_PAGO_MANTTO
    SET
        ID_USER = @ID_USER,
        ID_TIPO_PAGO = @ID_TIPO_PAGO,
        MONTO = @MONTO,
        FE_PAGO = @FE_PAGO,
        ID_ESTADO = @ID_ESTADO,
        COMPROBANTE = @COMPROBANTE
    WHERE ID_PAGO_MANTTO = @ID_PAGO_MANTTO
END
GO