SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TRZ6_ROL'
ORDER BY ORDINAL_POSITION
GO

SELECT * FROM TRZ6_ROL GO

-- Listar roles por estado
CREATE PROCEDURE SP_L_ROL_01
    @ESTADO INT
AS
BEGIN
    SELECT
        ROL_ID,
        ROL_NOM,
        FEC_CREA,
        ESTADO
    FROM TRZ6_ROL
    WHERE ESTADO = @ESTADO
    ORDER BY ROL_ID DESC
END
GO

-- Obtener rol por ID
CREATE PROCEDURE SP_O_ROL_01
    @ROL_ID INT
AS
BEGIN
    SELECT
        ROL_ID,
        ROL_NOM,
        FEC_CREA,
        ESTADO
    FROM TRZ6_ROL
    WHERE ROL_ID = @ROL_ID
END
GO

-- Eliminar rol por ID
CREATE PROCEDURE SP_D_ROL_01
    @ROL_ID INT
AS
BEGIN
    DELETE FROM TRZ6_ROL
    WHERE ROL_ID = @ROL_ID
END
GO

-- Insertar nuevo rol
CREATE PROCEDURE SP_I_ROL_01
    @ROL_NOM VARCHAR(100),
    @ESTADO INT
AS
BEGIN
    INSERT INTO TRZ6_ROL (
        ROL_NOM,
        FEC_CREA,
        ESTADO
    )
    VALUES (
        @ROL_NOM,
        SYSUTCDATETIME(),
        @ESTADO
    )
END
GO

-- Actualizar rol
CREATE PROCEDURE SP_U_ROL_01
    @ROL_ID INT,
    @ROL_NOM VARCHAR(100),
    @ESTADO INT
AS
BEGIN
    UPDATE TRZ6_ROL
    SET
        ROL_NOM = @ROL_NOM,
        ESTADO = @ESTADO
    WHERE ROL_ID = @ROL_ID
END
GO